cars = ['bmw', 'audi', 'toyota', 'subaru']
print(sorted(cars,reverse=True))
print(cars)
cars.reverse()
print(cars)
print(len(cars))

places = ['shenzhen', 'chengdu', 'tokyo', 'seattle', 'new york']
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
print(len(places))
